# Project Aims
_Generated by Crucible on {{date}}. Edit anytime; re-run `/crucible:aims` to refresh._

## What this project is
{{project_description}}

## Goal
{{goal}}

## Success criteria
{{#each success_criteria}}
- {{this}}
{{/each}}

## Non-goals / out of scope
{{#each non_goals}}
- {{this}}
{{/each}}

## Tech stack (detected)
- **Languages:** {{languages}}
- **Frameworks:** {{frameworks}}
- **Datastores:** {{datastores}}
- **Deployment:** {{deployment}}

## Project type
{{project_type}}

## Constraints
{{#each constraints}}
- {{this}}
{{/each}}

---
_Last refreshed: {{timestamp}}_
